### ISSUE TITLE
Improvement: Print Google Geocoding Status codes when not 'OK'

### ISSUE THREAD

**Issue by PaulMorel** [getkirby-v2/geo-plugin#1]
I've skimmed over the plugin and it looks really nice and clean. One thing I didn't see was managing status codes. (I might have missed it)

For example, if you give the API a bad address (https://maps.googleapis.com/maps/api/geocode/json?address=dgsgdgd) it still returns a legit JSON response, but with no results and a status code other than "OK".

I had this issue with another Geocoding plugin for Wordpress where the plugin would silently fail without telling us why. Turns out we had hit our API key geocoding limit and getting 'OVER_QUERY_LIMIT' statuses, but the headers were still 200 OK.

Just an idea.

**Comment by bastianallgeier** [comment]
In case of an invalid response or if something cannot be parsed, the plugin should actually return false instead of a valid Kirby Geo Point. So you can check for that and react on it.

**Comment by flokosiol** [comment]
I had the same issue. The request was handled correctly, but Google Maps API returned the status "ZERO_RESULTS".
```json
...
["error"]=>
  int(0)
  ["message"]=>
  string(0) ""
  ["content"]=>
  string(52) "{
   "results" : [],
   "status" : "ZERO_RESULTS"
}
"
  ["code"]=>
  int(200)
...
```
The problem was that the plugin tried to create geo points [here](https://github.com/getkirby-plugins/geo-plugin/blob/master/lib/geo.php#L122) which leads to an Exception. I fixed it by [adding a simple check](https://github.com/flokosiol/geo-plugin/blob/master/lib/geo.php#L122).
